# Generated by Django 5.1.7 on 2025-03-07 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='שם מלא')),
                ('personal_id', models.CharField(max_length=20, verbose_name='מספר אישי')),
                ('team', models.CharField(max_length=100, verbose_name='צוות')),
                ('referral_type', models.CharField(choices=[('specialist', 'רופא מומחה'), ('imaging', 'בדיקות דימות'), ('lab', 'בדיקות מעבדה'), ('procedure', 'פרוצדורה'), ('other', 'אחר')], max_length=50, verbose_name='סוג הפנייה')),
                ('referral_details', models.CharField(max_length=255, verbose_name='הפניה מבוקשת')),
                ('has_documents', models.BooleanField(default=False, verbose_name='האם יש אסמכתא')),
                ('priority', models.CharField(choices=[('low', 'נמוכה'), ('medium', 'בינונית'), ('high', 'גבוהה'), ('urgent', 'דחופה'), ('immediate', 'מיידית'), ('routine', 'שגרתית'), ('elective', 'אלקטיבית'), ('emergency', 'חירום')], default='medium', max_length=20, verbose_name='עדיפות')),
                ('status', models.CharField(choices=[('appointment_scheduled', 'נקבע תור'), ('requires_coordination', 'דרוש תיאום'), ('completed', 'בוצע הושלם'), ('waiting_for_budget_approval', 'ממתין לאישור תקציבי'), ('waiting_for_doctor_referral', 'ממתין להפניה מרופא')], default='appointment_scheduled', max_length=50, verbose_name='סטטוס')),
                ('appointment_date', models.DateTimeField(blank=True, null=True, verbose_name='תאריך התור')),
                ('appointment_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='מסלול')),
                ('appointment_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='מיקום התור')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך כניסה למערכת')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='תאריך עדכון')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_referrals', to=settings.AUTH_USER_MODEL, verbose_name='נוצר על ידי')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_referrals', to=settings.AUTH_USER_MODEL, verbose_name='עודכן לאחרונה על ידי')),
            ],
            options={
                'verbose_name': 'הפניה רפואית',
                'verbose_name_plural': 'הפניות רפואיות',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='referral_documents/%Y/%m/', verbose_name='קובץ')),
                ('title', models.CharField(max_length=255, verbose_name='כותרת')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='תאריך העלאה')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='referrals.referral', verbose_name='הפניה')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='הועלה על ידי')),
            ],
            options={
                'verbose_name': 'מסמך הפניה',
                'verbose_name_plural': 'מסמכי הפניה',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['full_name'], name='referrals_r_full_na_22c45b_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['personal_id'], name='referrals_r_persona_c62472_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['team'], name='referrals_r_team_a9ab44_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['status'], name='referrals_r_status_50a3e5_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['priority'], name='referrals_r_priorit_bf044d_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['appointment_date'], name='referrals_r_appoint_ea93e1_idx'),
        ),
    ]
