# Generated by Django 5.1.7 on 2025-03-07 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_rename_referrals_r_referen_123456_idx_referrals_r_referen_e4d77d_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together={('personal_id', 'referral_type', 'referral_details')},
        ),
    ]
