# Generated by Django 5.1.7 on 2025-03-07 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='מפתח')),
                ('value', models.JSONField(verbose_name='ערך')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר בתאריך')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='עודכן לאחרונה בתאריך')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_settings', to=settings.AUTH_USER_MODEL, verbose_name='נוצר על ידי')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL, verbose_name='עודכן לאחרונה על ידי')),
            ],
            options={
                'verbose_name': 'הגדרת מערכת',
                'verbose_name_plural': 'הגדרות מערכת',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='כתובת IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='תאריך ושעה')),
                ('action_type', models.CharField(choices=[('create', 'יצירה'), ('update', 'עדכון'), ('delete', 'מחיקה'), ('login', 'התחברות'), ('logout', 'התנתקות'), ('view', 'צפייה'), ('export', 'ייצוא'), ('other', 'אחר')], max_length=50, verbose_name='סוג פעולה')),
                ('action_detail', models.CharField(max_length=255, verbose_name='פרטי פעולה')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='מזהה אובייקט')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='ערכים ישנים')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='ערכים חדשים')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='סוג תוכן')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='משתמש')),
            ],
            options={
                'verbose_name': 'תיעוד פעולה',
                'verbose_name_plural': 'תיעוד פעולות',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='audit_audit_user_id_292c79_idx'), models.Index(fields=['action_type'], name='audit_audit_action__dd3a3c_idx'), models.Index(fields=['timestamp'], name='audit_audit_timesta_19e18a_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_4c2ead_idx')],
            },
        ),
    ]
